### ISSUE TITLE
How to place it the top first one?

### ISSUE THREAD

**Issue by sudg6** [vanlocvo/Nautilus-OpenInVSCode#2]
I'd like to see "Open with VS Code" as the first option in the context menu is that possible?

**Comment by vanlocvo** [comment]
I think we can't change positions, but I will check when I have time :3

**Comment by anthonyleestark** [comment]
> I think we can't change positions, but I will check when I have time :3

You can't set the absolute first position, but you can bring your item to the top by setting a higher priority
This may work:
``` python
def _create_nautilus_item(self, file, location):
		"""Creates the 'Open with VSCode' menu item."""
		item = Nautilus.MenuItem(name="VSCodeNautilus::Nautilus"+location,
		                         label=gettext("Open in Code"),
		                         tip=gettext("Open this folder/file in VSCode"))
		item.connect("activate", self._nautilus_run, file)
		item.set_property("priority", 0.0)
		return item 
```
