### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by Commenter25** [vanlocvo/Nautilus-OpenInVSCode#8]
Currently, the script cannot find the flatpak versions of either VSCode or VSCodium. Flatpaks and even immutable distros are rising in popularity, and the Codium flatpak is officially maintained and supported, so it makes sense to support these.

**Comment by vanlocvo** [comment]
Thanks, I will check it soon

**Comment by vanlocvo** [comment]
Flatpak was supported with this commit [fafc1f92aed9a43b85336ec4beb094290db9a2f5](https://github.com/vanlocvo/Nautilus-OpenInVSCode/commit/fafc1f92aed9a43b85336ec4beb094290db9a2f5)
